name: Ruby

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: 3.1
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake
        env:
          BNET_APPLICATION_ID: ${{ secrets.BNET_APPLICATION_ID }}
          BNET_APPLICATION_SECRET: ${{ secrets.BNET_APPLICATION_SECRET }}
          USE_CACHE: false
          IGNORE_CLASSIC_TESTS: true
